# Customer Churn Prediction

# Milestone 4: Data Preprocessing

## Objective

The goal of preprocessing is to transform the raw dataset into a clean and machine-learning-ready format.

The preprocessing steps include:

- Removing unnecessary features
- Handling missing values
- Correcting data types
- Encoding categorical variables
- Splitting the dataset
- Scaling numerical features
- Handling class imbalance using SMOTE

# Preprocessing Strategy

| Feature | Data Type | Action | Reason |
|----------|-----------|--------|--------|
| customerID | Identifier | Drop | Unique identifier, no predictive value |
| gender | Categorical | One-Hot Encode | Convert to numeric |
| SeniorCitizen | Numeric | Keep | Already numeric |
| Partner | Categorical | One-Hot Encode | Convert to numeric |
| Dependents | Categorical | One-Hot Encode | Convert to numeric |
| tenure | Numeric | Scale | Different numerical range |
| PhoneService | Categorical | One-Hot Encode | Convert to numeric |
| MultipleLines | Categorical | One-Hot Encode | Convert to numeric |
| InternetService | Categorical | One-Hot Encode | Convert to numeric |
| OnlineSecurity | Categorical | One-Hot Encode | Convert to numeric |
| OnlineBackup | Categorical | One-Hot Encode | Convert to numeric |
| DeviceProtection | Categorical | One-Hot Encode | Convert to numeric |
| TechSupport | Categorical | One-Hot Encode | Convert to numeric |
| StreamingTV | Categorical | One-Hot Encode | Convert to numeric |
| StreamingMovies | Categorical | One-Hot Encode | Convert to numeric |
| Contract | Categorical | One-Hot Encode | Convert to numeric |
| PaperlessBilling | Categorical | One-Hot Encode | Convert to numeric |
| PaymentMethod | Categorical | One-Hot Encode | Convert to numeric |
| MonthlyCharges | Numeric | Scale | Normalize values |
| TotalCharges | Numeric | Convert + Scale | Incorrect data type |
| Churn | Target | Label Encode | Binary target |

In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [2]:
import pandas as pd

from src.preprocessing import clean_data

In [3]:
df = pd.read_csv("../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
df = clean_data(df)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

## Investigating Missing Values

Before deciding how to handle missing values, we inspect the affected rows to understand why the values are missing.

In [5]:
df[df["TotalCharges"].isnull()]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [6]:
df[df["TotalCharges"].isnull()][
    ["tenure", "MonthlyCharges", "TotalCharges"]
]

      tenure  MonthlyCharges  TotalCharges
488        0           52.55           NaN
753        0           20.25           NaN
936        0           80.85           NaN
1082       0           25.75           NaN
1340       0           56.05           NaN
3331       0           19.85           NaN
3826       0           25.35           NaN
4380       0           20.00           NaN
5218       0           19.70           NaN
6670       0           73.35           NaN
6754       0           61.90           NaN

In [7]:
from src.preprocessing import handle_missing_values

In [8]:
df = clean_data(df)

print(df.shape)

df = handle_missing_values(df)

print(df.shape)

(7043, 20)
(7032, 20)

In [9]:
from src.preprocessing import encode_target

df = encode_target(df)

df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [10]:
from src.preprocessing import split_data

X_train, X_test, y_train, y_test = split_data(df)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (5625, 19)
Testing Features  : (1407, 19)
Training Labels   : (5625,)
Testing Labels    : (1407,)

In [11]:
print(y_train.value_counts(normalize=True))

print()

print(y_test.value_counts(normalize=True))

Churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64

Churn
0    0.734186
1    0.265814
Name: proportion, dtype: float64

In [12]:
from src.preprocessing import create_preprocessor

preprocessor = create_preprocessor()

X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [13]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(5625, 45)
(1407, 45)

In [14]:
from src.preprocessing import apply_smote

X_train_smote, y_train_smote = apply_smote(
    X_train_processed,
    y_train
)

In [15]:
print(X_train_smote.shape)
print(y_train_smote.shape)

print(y_train.value_counts())

print()

print(y_train_smote.value_counts())

(8260, 45)
(8260,)
Churn
0    4130
1    1495
Name: count, dtype: int64

Churn
0    4130
1    4130
Name: count, dtype: int64

# Preprocessing Summary

The preprocessing pipeline prepared the dataset for machine learning by:

- Removing the identifier column (`customerID`)
- Converting `TotalCharges` to numeric
- Removing rows with missing values
- Encoding the target variable (`Churn`)
- Splitting the dataset into training and testing sets using stratification
- Applying a `ColumnTransformer` to preprocess numerical and categorical features
- Balancing the training data using SMOTE

The dataset is now ready for model training.